### IMPORTANT, THIS IMAGE CAN ONLY BE RUN IN LINUX DOCKER
### You will run into a segfault in mac
FROM python:3.11.6-slim-bookworm as base

# Install poetry
RUN pip install pipx
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"
ENV PATH=".venv/bin/:$PATH"

# Dependencies to build llama-cpp
RUN apt update && apt install -y \
  libopenblas-dev\
  ninja-build\
  build-essential\
  pkg-config\
  wget

# https://python-poetry.org/docs/configuration/#virtualenvsin-project
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/app
COPY pyproject.toml poetry.lock ./

RUN poetry install --extras "ui embeddings-huggingface llms-llama-cpp vector-stores-qdrant llms-openai embeddings-openai rerank-sentence-transformers"

FROM base as app

ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080

# Prepare a non-root user
WORKDIR /home/app

#RUN mkdir local_data;
#RUN mkdir models;
COPY models/ models
COPY local_data/ local_data
COPY  --from=dependencies /home/app/.venv/ .venv
COPY  private_gpt/ private_gpt
COPY  fern/ fern
COPY  *.yaml *.md ./


ENTRYPOINT python -m private_gpt